# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:59:29+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query, UploadFile

from models import (
    ApiDataentitiesAcronymDocumentsIdClustersPostRequest,
    ApiDataentitiesAcronymDocumentsIdPatchRequest,
    ApiDataentitiesAcronymDocumentsIdPutRequest,
    ApiDataentitiesAcronymDocumentsIdScorePutRequest,
    ApiDataentitiesAcronymDocumentsIdVersionsGetResponse,
    ApiDataentitiesAcronymDocumentsPatchRequest,
    ApiDataentitiesAcronymDocumentsPostRequest,
    ApiDataentitiesAcronymDocumentsPutRequest,
    ApiDataentitiesGetResponse,
    Createnewdocument,
    DeletescorebyfieldRequest,
    Getdataentityfields,
    Getversion,
    PutscorebyfieldRequest,
    Putversion,
    Usingfilters,
)

app = MCPProxy(
    contact={},
    description='',
    title='MasterData API - v1',
    version='1.0',
    servers=[
        {'url': 'https://vtex.local'},
        {
            'description': 'VTEX server url',
            'url': 'https://{accountName}.{environment}.com.br',
            'variables': {
                'accountName': {
                    'default': '{accountName}',
                    'description': 'Name of the VTEX account. Used as part of the URL',
                },
                'environment': {
                    'default': '{environment}',
                    'description': 'Environment to use. Used as part of the URL.',
                },
            },
        },
    ],
)


@app.get(
    '/api/dataentities',
    description=""" Retrieves the list of existing data entities in the store.

### Response status code

1. Status Code `403`: Access not allowed
2. Status Code `200`: Retrieves data entity list

> All headers listed below are required. """,
    tags=['data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def listdataentities(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
):
    """
    List data entities
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}',
    description=""" Returns the data entity structure with its respective fields and data type.

### Response status code

1. Status Code `403`: Access not allowed
2. Status Code `200`: Retrieves data entity structure

> All headers listed below are required. """,
    tags=['data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def getdataentitystructure(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
):
    """
    Get data entity structure
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/dataentities/{acronym}/documents',
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def createorupdatepartialdocument(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    body: ApiDataentitiesAcronymDocumentsPatchRequest = ...,
):
    """
    Create or update partial document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/dataentities/{acronym}/documents',
    description=""" Creates documents through a JSON object where the key is the name of the field. """,
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def createnewdocument(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    body: ApiDataentitiesAcronymDocumentsPostRequest = ...,
):
    """
    Create new document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/dataentities/{acronym}/documents',
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def createorupdateentiredocument(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    body: ApiDataentitiesAcronymDocumentsPutRequest = ...,
):
    """
    Create or update entire document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/dataentities/{acronym}/documents/{id}',
    description=""" It allows to delete a document. """,
    tags=['document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def deletedocument(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
):
    """
    Delete document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/documents/{id}',
    description=""" Retrieves a document.

Assign the `_fields` parameter in the query string to retrieve the desired fields. If you want to return all the fields use `_fields=_all`. """,
    tags=['document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def getdocument(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
):
    """
    Get document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/dataentities/{acronym}/documents/{id}',
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def updatepartialdocument(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    body: ApiDataentitiesAcronymDocumentsIdPatchRequest = ...,
):
    """
    Update partial document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/dataentities/{acronym}/documents/{id}',
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def updateentiredocument(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    body: ApiDataentitiesAcronymDocumentsIdPutRequest = ...,
):
    """
    Update entire document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/dataentities/{acronym}/documents/{id}/clusters',
    tags=['document_management', 'data_entity_operations'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def validate_documentby_clusters(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    body: ApiDataentitiesAcronymDocumentsIdClustersPostRequest = ...,
):
    """
    Validate Document by Clusters
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/dataentities/{acronym}/documents/{id}/score',
    description=""" It allows punctuate in more than one field and more than one key. """,
    tags=['score_management', 'document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def putscores(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    body: ApiDataentitiesAcronymDocumentsIdScorePutRequest = ...,
):
    """
    Put scores
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/dataentities/{acronym}/documents/{id}/score/{field-name}',
    description=""" Allows you to remove a key from a specific field. """,
    tags=['score_management', 'document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def deletescorebyfield(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    field_name: str = Path(..., alias='field-name'),
    body: DeletescorebyfieldRequest = ...,
):
    """
    Delete score by field
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/dataentities/{acronym}/documents/{id}/score/{field-name}',
    description=""" It allows to punctuate in a specific field. """,
    tags=['score_management', 'document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def putscorebyfield(
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    field_name: str = Path(..., alias='field-name'),
    body: PutscorebyfieldRequest = ...,
):
    """
    Put score by field
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/documents/{id}/versions',
    description=""" Allows to list the versions of a document. """,
    tags=['document_versioning'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def listversions(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
):
    """
    List versions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/documents/{id}/versions/{versionId}',
    description=""" Returns the version of a document. """,
    tags=['document_versioning'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def getversion(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    version_id: str = Path(..., alias='versionId'),
):
    """
    Get version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/dataentities/{acronym}/documents/{id}/versions/{versionId}',
    description=""" Updates document with version values. """,
    tags=['document_versioning'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def putversion(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    version_id: str = Path(..., alias='versionId'),
):
    """
    Put version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/dataentities/{acronym}/documents/{id}/{field}/attachments',
    description=""" This API allows you to save a file in a field of type `File`.


When using in javascript, you must add the header `content-type` with value `multipart/form-data;`


You can upload more than one file. Just add a new field in the `form-data` with type `File`. """,
    tags=['attachment_handling'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def saveattachment(
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    field: str = '{{field}}',
    file: UploadFile = ...,
):
    """
    Save attachment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/documents/{id}/{field}/attachments/{file-name}',
    description=""" Use this API to retrieve a file.

Be sure to include the file extension in the name. Like in this example:
```
/dataentities/CL/documents/123/file/attachments/image.png
``` """,
    tags=['attachment_handling', 'document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def retrieveattachment(
    acronym: str = '{{acronym}}',
    id: str = '{{id}}',
    field: str = '{{field}}',
    file_name: str = Path(..., alias='file-name'),
):
    """
    Retrieve attachment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/scroll',
    description=""" Scrolls through documents according to the query parameter filters.


> Avoid sending too many requests with wildcards (`*`) in the search parameters or that use the `keyword` parameter. This may lead to this endpoint being temporarily blocked for your account. If this happens you will receive an error with status code `429`.


Use all the features of `search` API to perform filters.

In the first request, the `X-VTEX-MD-TOKEN` token will be obtained in the header. This token must be passed to the next request in the query string `_token` parameter. The token has a timeout of 10 minutes, which refreshes after each request.

**ATTENTION:** To inform the number of documents per request, use the query string parameter `_size`, which has the maximum value of 1000.

After the token is obtained it is no longer necessary to send the filter or document size per page parameters. You only need to resend the token until the document collection is empty.

### First request example:
```
/dataentities/CL/scroll?isCluster=true&_size=250&_fields=email,firstName
```

After the first request, retrieve the token in the header `X-VTEX-MD-TOKEN` and make the next requests.

### Example of subsequent requests:
```
/dataentities/CL/scroll?_token=tokenvalueexample
``` """,
    tags=['document_management', 'document_search'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def scrolldocuments(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    acronym: str = '{{acronym}}',
):
    """
    Scroll documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/dataentities/{acronym}/search',
    description=""" Search documents by the query parameters described below.


> Avoid sending too many requests with wildcards (`*`) in the search parameters or that use the `keyword` parameter. This may lead to this endpoint being temporarily blocked for your account. If this happens you will receive an error with status code `503`. """,
    tags=['document_search', 'document_management'],
    security=[
        APIKeyHeader(name="X-VTEX-API-AppKey"),
        APIKeyHeader(name="X-VTEX-API-AppToken"),
    ],
)
def searchdocuments(
    content__type: str = Header(..., alias='Content-Type'),
    accept: str = Header(..., alias='Accept'),
    r_e_s_t__range: str = Header(..., alias='REST-Range'),
    acronym: str = '{{acronym}}',
    field_fields: Optional[str] = Query('email,firstName,document', alias='_fields'),
    field_where: Optional[str] = Query('firstName is not null', alias='_where'),
    field_schema: Optional[str] = Query('{{schema}}', alias='_schema'),
    field_keyword: Optional[str] = Query('String to search', alias='_keyword'),
    field_sort: Optional[str] = Query('firstName ASC', alias='_sort'),
):
    """
    Search documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
