# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:59:29+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel


class ArEVentilaO(BaseModel):
    Date: str
    Point: int
    Until: str


class Createnewdocument(BaseModel):
    Href: str
    Id: str


class CreatenewdocumentRequest(BaseModel):
    Boolean: bool
    Currency: float
    Date: str
    Date_Time: str
    Decimal: float
    Email: str
    Integer: int
    Long: int
    Percent: float
    Relationship: str
    Text: str
    Time: str
    URL: str
    Varchar10: str
    Varchar100: str
    Varchar50: str
    Varchar750: str


class CreateorupdateentiredocumentRequest(BaseModel):
    Boolean: bool
    Currency: float
    Date: str
    Date_Time: str
    Decimal: float
    Email: str
    Integer: int
    Long: int
    Percent: float
    Relationship: str
    Text: str
    Time: str
    URL: str
    Varchar10: str
    Varchar100: str
    Varchar50: str
    Varchar750: str
    id: str


class CreateorupdatepartialdocumentRequest(BaseModel):
    Boolean: bool
    id: str


class DeletescorebyfieldRequest(BaseModel):
    key: str


class FieldModel(BaseModel):
    displayName: str
    isFilter: bool
    isInternal: bool
    isNullable: bool
    isSearchable: bool
    name: str
    type: str


class Getdataentityfields(BaseModel):
    acronym: str
    allowGetAll: bool
    fields: List[FieldModel] = Field(..., description='')
    name: str
    primaryKeyType: str


class Listdataentity(BaseModel):
    acronym: str
    allowGetAll: bool
    name: str
    primaryKeyType: str


class Listversion(BaseModel):
    date: str
    id: str


class PutscorebyfieldRequest(BaseModel):
    key: str
    point: int
    until: str


class PutscoresRequest(BaseModel):
    field: str
    key: str
    point: int
    until: str


class Putversion(BaseModel):
    Href: str
    Id: str


class Scores(BaseModel):
    Ar_e_Ventilação: List[ArEVentilaO] = Field(
        ..., alias='Ar e Ventilação', description=''
    )


class UpdateentiredocumentRequest(BaseModel):
    Boolean: bool
    Currency: float
    Date: str
    Date_Time: str
    Decimal: float
    Email: str
    Integer: int
    Long: int
    Percent: float
    Relationship: str
    Text: str
    Time: str
    URL: str
    Varchar10: str
    Varchar100: str
    Varchar50: str
    Varchar750: str


class UpdatepartialdocumentRequest(BaseModel):
    Boolean: bool


class Usingfilters(BaseModel):
    campo1: str
    campo2: str
    campo3: int


class ValidateDocumentbyClustersRequest(BaseModel):
    name: str
    rule: str


class ApiDataentitiesGetResponse(RootModel[List[Listdataentity]]):
    root: List[Listdataentity]


class ApiDataentitiesAcronymDocumentsPatchRequest(BaseModel):
    pass


class ApiDataentitiesAcronymDocumentsPostRequest(BaseModel):
    pass


class ApiDataentitiesAcronymDocumentsPutRequest(BaseModel):
    pass


class ApiDataentitiesAcronymDocumentsIdPatchRequest(BaseModel):
    pass


class ApiDataentitiesAcronymDocumentsIdPutRequest(BaseModel):
    pass


class ApiDataentitiesAcronymDocumentsIdClustersPostRequest(RootModel[List]):
    root: List


class ApiDataentitiesAcronymDocumentsIdScorePutRequest(
    RootModel[List[PutscoresRequest]]
):
    root: List[PutscoresRequest] = Field(..., description='')


class ApiDataentitiesAcronymDocumentsIdVersionsGetResponse(
    RootModel[List[Listversion]]
):
    root: List[Listversion]


class ApiDataentitiesAcronymDocumentsIdFieldAttachmentsPostRequest(BaseModel):
    file: List[bytes]


class DepartmentVisitedTag(BaseModel):
    DisplayValue: str
    Scores_1: Scores = Field(..., alias='Scores')


class Document(BaseModel):
    accountId: str
    accountName: str
    carttag: str
    checkouttag: str
    dataEntityId: str
    departmentVisitedTag: DepartmentVisitedTag
    email: str
    followers: List[str] = Field(..., description='')
    id: str
    rclastsession: str
    rclastsessiondate: str


class Getversion(BaseModel):
    author: str
    document: Document
    id: str
